### ISSUE TITLE
Check/Uncheck list item reorders items. Items do not stay at same order.

### ISSUE THREAD

**Issue by xet7** [fredmaiaarantes/simpletasks#13]
Hi,
Check/Uncheck list item reorders items. Items do not stay at same order.

How to fix?

**Comment by xet7** [comment]
It looks likes that this only happens to original 3 pre-existing list items. When I remove them, and add new list items, they stay at same order, when checking/unchecking list items.

**Comment by fredmaiaarantes** [comment]
Hi @xet7, thanks for reporting this.

Tasks are ordered by creation date, but since these pre-existing tasks were added with the same date and time, their order is random.

I changed the `useFind()` sorting to consider the task description and changed tasks migration to set different dates for each task.
